# Generated by Django 5.1.4 on 2025-01-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='Gender',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='Role',
            field=models.CharField(max_length=15),
        ),
    ]
